name: service_dashboard
description: "Metro Services"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  # Flutter SDK and Basic Packages
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management and Core Libraries
  get: ^4.6.6
  dio: ^5.7.0
  sendgrid_mailer: ^0.1.3

  # Charting and Advanced Visualization
  fl_chart: ^0.70.1
  percent_indicator: ^4.2.4

  # Email Sending and Communication Packages
  mailer: ^6.4.1

  # UI and Animation Packages
  flutter_svg: ^2.0.9
  lottie: ^3.0.0

  # PDF and Document Handling
  pdf: ^3.11.1

dev_dependencies:
  # Testing and Linter Tools
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # App Icons and Fonts
    - assets/icons/
    - assets/fonts/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios : true
  background_color: "#FFFFFFFF"
  image_path: "assets/icons/app_icon_white.png"
  min_sdk_android: 21
  web:
    generate: true
    background_color: "#FFFFFFFF"
    image_path: "assets/icons/app_icon_white.png"
    theme_color: "#FFFFFFFF"
